version: 1
disable_existing_loggers: False
formatters:
  default:
    (): 'uvicorn.logging.DefaultFormatter'
    format: '[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S %z'
  access:
    (): 'uvicorn.logging.AccessFormatter'
    format: '[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S %z'
handlers:
  error_console:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  console:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - error_console
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - console
    propagate: no
  depolarizing_chatroom:
    level: DEBUG
    handlers:
      - error_console