"""Initial migration

Revision ID: fe484280aa78
Revises: 
Create Date: 2022-01-12 15:39:56.628267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe484280aa78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('bot', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('msg_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'msg_count')
    op.drop_column('messages', 'bot')
    # ### end Alembic commands ###
